version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: ./shop/Dockerfile
    ports:
      - "12345:12345"
    depends_on: 
      - mongo
    environment: 
      MONGO_SHOP_DB_NAME: "testing"
      MONGO_ITEMS_COLL_NAME: "items"
      MONGO_USERS_COLL_NAME: "users"
      EXTERNAL_LISTEN_PORT: "12345"
      MONGO_CONN_STRING: "mongodb://mongodb:27017"
      JWT_HS256_SECRET: "qwerty12345"
      REFRESH_TOKENS_DURATION_MINUTES: 10
      ACCESS_TOKENS_DURATION_MINUTES: 5
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
    command: mongod --logpath=/dev/null
