version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./shop/Dockerfile
    ports:
      - "12345:12345"
    depends_on: 
      - mongo
    environment: 
      MONGO_SHOP_DB_NAME: "testing"
      MONGO_ITEMS_COLL_NAME: "items"
      EXTERNAL_LISTEN_PORT: "12345"
      MONGO_CONN_STRING: "mongodb://mongodb:27017"
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null
 