version: '3.4'

x-common-variables: &common-variables
  MONGO_CONN_STRING: "mongodb://mongodb:27017"
  RABBIT_MQ_CONN_STRING: "amqp://guest:guest@rabbitmq:5672/"
  MONGO_SHOP_DB_NAME: "testing"

services:
  backend:
    build: 
      context: .
      dockerfile: ./shop/Dockerfile
    ports:
      - "12345:12345"
    depends_on: 
      - mongo
    environment: 
      <<: *common-variables
      AUTH_VALIDATION_ROUTE: "http://auth:54321/validate"
      MONGO_ITEMS_COLL_NAME: "items"
      EXTERNAL_LISTEN_PORT: "12345"
  auth:
    container_name: "auth"
    ports:
      - "54321:54321"
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    depends_on: 
      - mongo
    environment:
      <<: *common-variables
      INTERNAL_LISTEN_PORT: "54321"
      NOTIFIER_REQ_ROUTE: "http://notifier:3435/notify"
      AUTH_CONFIRM_ROUTE: "http://localhost:54321/confirm"
      MONGO_PENDING_USERS_COLL_NAME: "pending_users"
      MONGO_ACTIVE_USERS_COLL_NAME: "active_users"
      JWT_HS256_SECRET: "qwerty12345"
      ACCESS_TOKENS_DURATION_MINUTES: 5
      REFRESH_TOKENS_DURATION_MINUTES: 10
      ACC_CONFIRMATION_DURATION_SECS: 60
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
    command: mongod --logpath=/dev/null
  notifier:
    container_name: "notifier"
    build: 
      context: .
      dockerfile: ./notifier/Dockerfile
    ports:
      - "3435:3435"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      <<: *common-variables
      INTERNAL_LISTEN_PORT: "3435"
      NOTIFIER_CHAN_NAME: "notifications"
  notifier-handler-mock:
    build:
      context: .
      dockerfile: ./notifier-handler-mock/Dockerfile
    depends_on: 
      - rabbitmq
    environment:
      <<: *common-variables
      NOTIFIER_CHAN_NAME: "notifications"
  # https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # manager on http://localhost:15672 (username: guest, pass: guest)
      - "5672:5672"

