version: '3'
services:
  backend:
    build: .
    ports:
      - "12345:12345"
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment: 
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null
 